# Register at https://openweathermap.org to get your API key
api_key = "c97797f67405a949ca5ff98ea438ec0a"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "6077243"

# Display settings
units = "metric"
display_symbol = "°C"
